name: Build IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # تم التحديث للنسخة 4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Project
        run: xcodegen generate

      - name: Build IPA
        run: |
          xcodebuild archive -scheme AetherWidgets -archivePath build.xcarchive -sdk iphoneos CODE_SIGNING_ALLOWED=NO
          mkdir -p Payload
          cp -r build.xcarchive/Products/Applications/*.app Payload/
          zip -r AetherWidgets.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4 # هذا هو السطر الذي سبب المشكلة وتم تصحيحه
        with:
          name: App-IPA
          path: AetherWidgets.ipa
